irradium-contrib/firefox: update 155.0.1 -> 156.0

diff --git a/irradium-contrib/firefox/Pkgfile b/irradium-contrib/firefox/Pkgfile
--- a/irradium-contrib/firefox/Pkgfile
+++ b/irradium-contrib/firefox/Pkgfile
@@ -5,11 +5,12 @@
 # Optional: apulse pulseaudio pipewire sndio sccache icu lld wayland xdg-desktop-portal-gtk
 
 name=firefox
-version=155.0.1
+version=156.0
 release=1
 source=(https://ftp.mozilla.org/pub/$name/releases/$version/source/$name-$version.source.tar.xz
   firefox.desktop
   fix-target-detection.patch
+  bugzilla2071536.patch
   node-stdout-nonblocking-wrapper
   rust-lto-thin.patch)
 
@@ -112,9 +113,9 @@ EOF
   [ -e /usr/lib/pkgconfig/sndio.pc ] && PKGMK_FFAUDIO+=",sndio"
   echo "ac_add_options --enable-audio-backends=${PKGMK_FFAUDIO}" >> .mozconfig
 
-  if prt-get isinst wayland xorg-server >/dev/null ; then
+  if [ -e /usr/lib/pkgconfig/xorg-server.pc ] && [ -e /usr/lib/pkgconfig/gtk+-wayland-3.0.pc ]; then
     echo 'ac_add_options --enable-default-toolkit=cairo-gtk3-x11-wayland' >> .mozconfig
-  elif prt-get isinst wayland >/dev/null ; then
+  elif [ -e /usr/lib/pkgconfig/gtk+-wayland-3.0.pc ]; then
     echo 'ac_add_options --enable-default-toolkit=cairo-gtk3-wayland-only' >> .mozconfig
   else
     echo 'ac_add_options --enable-default-toolkit=cairo-gtk3-x11-only' >> .mozconfig
@@ -133,7 +134,9 @@ EOF
   export CXXFLAGS="$CXXFLAGS -w"
   export LDFLAGS="$LDFLAGS -Wl,-rpath=/usr/lib/firefox,--enable-new-dtags"
 
-  if [ -x /usr/bin/clang ] && [ -x /usr/bin/lld ]; then
+  # Newer versions of clang fail to compile gl.cc
+  if command -v clang && command -v lld && clang --version \
+      | awk '(NR==1) {split($3,v,"."); if (v[1] >= 23) exit 1}'; then
       echo 'ac_add_options --enable-linker=lld' >> .mozconfig
       export LDFLAGS+=",--thinlto-jobs=$((${JOBS-2} / 2))"
       export CC=clang CXX=clang++
