irradium-contrib/firefox: update 125.0.3 -> 126.0

diff --git a/irradium-contrib/firefox/Pkgfile b/irradium-contrib/firefox/Pkgfile
--- a/irradium-contrib/firefox/Pkgfile
+++ b/irradium-contrib/firefox/Pkgfile
@@ -5,14 +5,12 @@
 # Optional: apulse jack pulseaudio pipewire sndio sccache lld wasi-libc++ wayland
 
 name=firefox
-version=125.0.3
+version=126.0
 release=1
 source=(https://ftp.mozilla.org/pub/$name/releases/$version/source/$name-$version.source.tar.xz
   firefox.desktop
   icu-linebreak-classes.patch
-  node-stdout-nonblocking-wrapper
-  lfs64.patch 01-rust-lto-thin.patch
-  02-riscv64-no-lto.patch)
+  node-stdout-nonblocking-wrapper)
 
 build() {
   cd $name-$version
@@ -22,8 +20,8 @@ build() {
   done
 
   if [ "$(/usr/bin/python3 -c "import sys; print(sys.stdout.encoding)")" != 'utf-8' ]; then
-  	printf "\e[031mError: set an UTF-8 locale to compile this!\033[0m\n"
-  	exit 1
+    printf "\e[031mError: set an UTF-8 locale to compile this!\033[0m\n"
+    exit 1
   fi
 
   prt-get isinst sccache && export RUSTC_WRAPPER='/usr/bin/sccache'
@@ -65,6 +63,13 @@ EOF
   if [ $(uname -m) != "riscv64" ]; then
     echo 'ac_add_options --disable-elf-hack' >> .mozconfig
   fi
+
+  # disable packed_simd with rust >= 1.78.0, because the bundled crate in this tarball 
+  # relies on a deprecated API (see https://bugzilla.mozilla.org/show_bug.cgi?id=1896958).
+  # But keep enabling the simd speedup for users who locked rust to an older version.
+  local rustVer=$(rustc --version | cut -d' ' -f2 | sed 's/\.[[:digit:]]*$//')
+  awk -v rV=$rustVer 'BEGIN { if ( rV < 1.78 ) print "ac_add_options --enable-rust-simd" }' \
+         >> .mozconfig
 
   # audio
   PKGMK_FFAUDIO="alsa"
